Fixed colcon build args
ros-navigation/nav2_docker pull request #5
Opened 2024-10-20 16:34 UTC by CihatAltiparmak

Added --symlink-install arg to colcon build command. Otherwise nav2_common may give build error.

2024-10-21 08:58 UTC, SteveMacenski commented
What error appeared? I generally prefer on a personal basis not to do symlinks, but that's not a good justification for keeping it that way if there's a technical reason to change it for Docker developer's use

2024-10-21 09:23 UTC, CihatAltiparmak commented
For my case, i'm trying to implement a kind of nav2 controller and when i compiled with `colcon build --packages-up-to nav2_frenet_ilqr_controller --symlink-install`, i receive some below error. (i sourced before)

```sh
root@jarbay51:~/nav2_ws# colcon build --packages-up-to nav2_frenet_ilqr_controller --symlink-install
Starting >>> nav2_common
Starting >>> frenet_trajectory_planner
--- stderr: nav2_common                                                                               
failed to create symbolic link '/root/nav2_ws/build/nav2_common/ament_cmake_python/nav2_common/nav2_common' because existing path cannot be removed: Is a directory
gmake[2]: *** [CMakeFiles/ament_cmake_python_symlink_nav2_common.dir/build.make:70: CMakeFiles/ament_cmake_python_symlink_nav2_common] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:138: CMakeFiles/ament_cmake_python_symlink_nav2_common.dir/all] Error 2
gmake: *** [Makefile:124: all] Error 2
---
Failed   <<< nav2_common [0.54s, exited with code 2]
Aborted  <<< frenet_trajectory_planner [1.33s]                            

Summary: 0 packages finished [1.50s]
  1 package failed: nav2_common
  1 package aborted: frenet_trajectory_planner
  1 package had stderr output: nav2_common
  9 packages not processed
root@jarbay51:~/nav2_ws# 
```

2024-10-27 11:40 UTC, SteveMacenski commented
Maybe worth having an ARG for build flags that you could use to set symlink install (or other potential mods).

2025-01-04 19:44 UTC, CihatAltiparmak commented
Sorry for loongg delay. Yeah, I guess you are right. So I have a offer. I can create a PR that aims to support additional compilation args at least for local docker builds.

Btw, fell free to close this out, looks like I have nothing I can do except some improvements I offer to you.

2025-01-04 23:40 UTC, SteveMacenski commented
That sounds good to me! Having an argument for build args to use would be welcome

2025-01-27 23:28 UTC, CihatAltiparmak commented
Finally I could made it. I have also updated the README. It is ready for you to  take a look.

2025-01-27 23:38 UTC, SteveMacenski requested changes
I'd just commit it myself and merge it, but it doesn't look like your fork will let me push to that branch

2025-01-27 23:38 UTC, SteveMacenski commented on README.md
> +Additionaly, if you want to build with customized arguments, you can add your build arguments as in the example `--build-arg COLCON_BUILD_ARGS="--symlink-install"`.
```suggestion
Additionally, if you want to build with customized arguments, you can add your build arguments as in the example `--build-arg COLCON_BUILD_ARGS="--symlink-install"`.
```

2025-01-27 23:38 UTC, merged